// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_base.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LoginCode int32

const (
	LoginCode_LCSuccess       LoginCode = 0
	LoginCode_LCSdkCheckFaild LoginCode = 1
	LoginCode_LCNoGame        LoginCode = 2
	LoginCode_LCCanNotReConn  LoginCode = 3
)

var LoginCode_name = map[int32]string{
	0: "LCSuccess",
	1: "LCSdkCheckFaild",
	2: "LCNoGame",
	3: "LCCanNotReConn",
}
var LoginCode_value = map[string]int32{
	"LCSuccess":       0,
	"LCSdkCheckFaild": 1,
	"LCNoGame":        2,
	"LCCanNotReConn":  3,
}

func (x LoginCode) String() string {
	return proto.EnumName(LoginCode_name, int32(x))
}
func (LoginCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type MsgKeyExchange struct {
	Encode int64 `protobuf:"zigzag64,1,opt,name=Encode,json=encode" json:"Encode,omitempty"`
	Decode int64 `protobuf:"zigzag64,2,opt,name=Decode,json=decode" json:"Decode,omitempty"`
}

func (m *MsgKeyExchange) Reset()                    { *m = MsgKeyExchange{} }
func (m *MsgKeyExchange) String() string            { return proto.CompactTextString(m) }
func (*MsgKeyExchange) ProtoMessage()               {}
func (*MsgKeyExchange) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *MsgKeyExchange) GetEncode() int64 {
	if m != nil {
		return m.Encode
	}
	return 0
}

func (m *MsgKeyExchange) GetDecode() int64 {
	if m != nil {
		return m.Decode
	}
	return 0
}

type MsgHeartBeat struct {
	Time int64 `protobuf:"zigzag64,1,opt,name=Time,json=time" json:"Time,omitempty"`
}

func (m *MsgHeartBeat) Reset()                    { *m = MsgHeartBeat{} }
func (m *MsgHeartBeat) String() string            { return proto.CompactTextString(m) }
func (*MsgHeartBeat) ProtoMessage()               {}
func (*MsgHeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *MsgHeartBeat) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type MsgGameHeartBeat struct {
	RoleCnt  int32  `protobuf:"zigzag32,1,opt,name=RoleCnt,json=roleCnt" json:"RoleCnt,omitempty"`
	EndPoint string `protobuf:"bytes,2,opt,name=EndPoint,json=endPoint" json:"EndPoint,omitempty"`
}

func (m *MsgGameHeartBeat) Reset()                    { *m = MsgGameHeartBeat{} }
func (m *MsgGameHeartBeat) String() string            { return proto.CompactTextString(m) }
func (*MsgGameHeartBeat) ProtoMessage()               {}
func (*MsgGameHeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *MsgGameHeartBeat) GetRoleCnt() int32 {
	if m != nil {
		return m.RoleCnt
	}
	return 0
}

func (m *MsgGameHeartBeat) GetEndPoint() string {
	if m != nil {
		return m.EndPoint
	}
	return ""
}

type MsgGameRoles struct {
	Roles []string `protobuf:"bytes,1,rep,name=Roles,json=roles" json:"Roles,omitempty"`
}

func (m *MsgGameRoles) Reset()                    { *m = MsgGameRoles{} }
func (m *MsgGameRoles) String() string            { return proto.CompactTextString(m) }
func (*MsgGameRoles) ProtoMessage()               {}
func (*MsgGameRoles) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *MsgGameRoles) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type MsgFtHeartBeat struct {
	EndPoint string `protobuf:"bytes,1,opt,name=EndPoint,json=endPoint" json:"EndPoint,omitempty"`
}

func (m *MsgFtHeartBeat) Reset()                    { *m = MsgFtHeartBeat{} }
func (m *MsgFtHeartBeat) String() string            { return proto.CompactTextString(m) }
func (*MsgFtHeartBeat) ProtoMessage()               {}
func (*MsgFtHeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *MsgFtHeartBeat) GetEndPoint() string {
	if m != nil {
		return m.EndPoint
	}
	return ""
}

type MsgGtHeartBeat struct {
	EndPoint string `protobuf:"bytes,1,opt,name=EndPoint,json=endPoint" json:"EndPoint,omitempty"`
	RoleCnt  int32  `protobuf:"zigzag32,2,opt,name=RoleCnt,json=roleCnt" json:"RoleCnt,omitempty"`
}

func (m *MsgGtHeartBeat) Reset()                    { *m = MsgGtHeartBeat{} }
func (m *MsgGtHeartBeat) String() string            { return proto.CompactTextString(m) }
func (*MsgGtHeartBeat) ProtoMessage()               {}
func (*MsgGtHeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *MsgGtHeartBeat) GetEndPoint() string {
	if m != nil {
		return m.EndPoint
	}
	return ""
}

func (m *MsgGtHeartBeat) GetRoleCnt() int32 {
	if m != nil {
		return m.RoleCnt
	}
	return 0
}

type MsgForwardToRole struct {
	MsgID    uint32 `protobuf:"varint,1,opt,name=MsgID,json=msgID" json:"MsgID,omitempty"`
	RoleGuid uint32 `protobuf:"varint,2,opt,name=RoleGuid,json=roleGuid" json:"RoleGuid,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
}

func (m *MsgForwardToRole) Reset()                    { *m = MsgForwardToRole{} }
func (m *MsgForwardToRole) String() string            { return proto.CompactTextString(m) }
func (*MsgForwardToRole) ProtoMessage()               {}
func (*MsgForwardToRole) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *MsgForwardToRole) GetMsgID() uint32 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

func (m *MsgForwardToRole) GetRoleGuid() uint32 {
	if m != nil {
		return m.RoleGuid
	}
	return 0
}

func (m *MsgForwardToRole) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MsgROnOffLine struct {
	Acc  string `protobuf:"bytes,1,opt,name=Acc,json=acc" json:"Acc,omitempty"`
	Guid uint32 `protobuf:"varint,2,opt,name=Guid,json=guid" json:"Guid,omitempty"`
}

func (m *MsgROnOffLine) Reset()                    { *m = MsgROnOffLine{} }
func (m *MsgROnOffLine) String() string            { return proto.CompactTextString(m) }
func (*MsgROnOffLine) ProtoMessage()               {}
func (*MsgROnOffLine) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *MsgROnOffLine) GetAcc() string {
	if m != nil {
		return m.Acc
	}
	return ""
}

func (m *MsgROnOffLine) GetGuid() uint32 {
	if m != nil {
		return m.Guid
	}
	return 0
}

type MsgAccInfo struct {
	GateEndPoint string `protobuf:"bytes,1,opt,name=GateEndPoint,json=gateEndPoint" json:"GateEndPoint,omitempty"`
}

func (m *MsgAccInfo) Reset()                    { *m = MsgAccInfo{} }
func (m *MsgAccInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgAccInfo) ProtoMessage()               {}
func (*MsgAccInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *MsgAccInfo) GetGateEndPoint() string {
	if m != nil {
		return m.GateEndPoint
	}
	return ""
}

// 登录请求
type MsgLogin struct {
	Acc     string   `protobuf:"bytes,1,opt,name=Acc,json=acc" json:"Acc,omitempty"`
	SesOnGt uint32   `protobuf:"varint,2,opt,name=SesOnGt,json=sesOnGt" json:"SesOnGt,omitempty"`
	GtID    uint32   `protobuf:"varint,3,opt,name=GtID,json=gtID" json:"GtID,omitempty"`
	Dev     string   `protobuf:"bytes,4,opt,name=Dev,json=dev" json:"Dev,omitempty"`
	Token   []string `protobuf:"bytes,5,rep,name=Token,json=token" json:"Token,omitempty"`
}

func (m *MsgLogin) Reset()                    { *m = MsgLogin{} }
func (m *MsgLogin) String() string            { return proto.CompactTextString(m) }
func (*MsgLogin) ProtoMessage()               {}
func (*MsgLogin) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *MsgLogin) GetAcc() string {
	if m != nil {
		return m.Acc
	}
	return ""
}

func (m *MsgLogin) GetSesOnGt() uint32 {
	if m != nil {
		return m.SesOnGt
	}
	return 0
}

func (m *MsgLogin) GetGtID() uint32 {
	if m != nil {
		return m.GtID
	}
	return 0
}

func (m *MsgLogin) GetDev() string {
	if m != nil {
		return m.Dev
	}
	return ""
}

func (m *MsgLogin) GetToken() []string {
	if m != nil {
		return m.Token
	}
	return nil
}

type MsgReLogin struct {
	Acc   string `protobuf:"bytes,1,opt,name=Acc,json=acc" json:"Acc,omitempty"`
	SesID uint32 `protobuf:"varint,2,opt,name=SesID,json=sesID" json:"SesID,omitempty"`
}

func (m *MsgReLogin) Reset()                    { *m = MsgReLogin{} }
func (m *MsgReLogin) String() string            { return proto.CompactTextString(m) }
func (*MsgReLogin) ProtoMessage()               {}
func (*MsgReLogin) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *MsgReLogin) GetAcc() string {
	if m != nil {
		return m.Acc
	}
	return ""
}

func (m *MsgReLogin) GetSesID() uint32 {
	if m != nil {
		return m.SesID
	}
	return 0
}

type MsgLoginAck struct {
	Ret    LoginCode `protobuf:"varint,1,opt,name=Ret,json=ret,enum=pb.LoginCode" json:"Ret,omitempty"`
	Data   *MsgLogin `protobuf:"bytes,2,opt,name=Data,json=data" json:"Data,omitempty"`
	GameID uint32    `protobuf:"varint,3,opt,name=GameID,json=gameID" json:"GameID,omitempty"`
}

func (m *MsgLoginAck) Reset()                    { *m = MsgLoginAck{} }
func (m *MsgLoginAck) String() string            { return proto.CompactTextString(m) }
func (*MsgLoginAck) ProtoMessage()               {}
func (*MsgLoginAck) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *MsgLoginAck) GetRet() LoginCode {
	if m != nil {
		return m.Ret
	}
	return LoginCode_LCSuccess
}

func (m *MsgLoginAck) GetData() *MsgLogin {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MsgLoginAck) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

type MsgLoadRole struct {
	Acc    string `protobuf:"bytes,1,opt,name=Acc,json=acc" json:"Acc,omitempty"`
	GameID uint32 `protobuf:"varint,2,opt,name=GameID,json=gameID" json:"GameID,omitempty"`
}

func (m *MsgLoadRole) Reset()                    { *m = MsgLoadRole{} }
func (m *MsgLoadRole) String() string            { return proto.CompactTextString(m) }
func (*MsgLoadRole) ProtoMessage()               {}
func (*MsgLoadRole) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *MsgLoadRole) GetAcc() string {
	if m != nil {
		return m.Acc
	}
	return ""
}

func (m *MsgLoadRole) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

type MsgReConn struct {
	Acc        string `protobuf:"bytes,1,opt,name=Acc,json=acc" json:"Acc,omitempty"`
	Guid       uint32 `protobuf:"varint,2,opt,name=Guid,json=guid" json:"Guid,omitempty"`
	Token      uint32 `protobuf:"varint,3,opt,name=Token,json=token" json:"Token,omitempty"`
	FightID    uint32 `protobuf:"varint,4,opt,name=FightID,json=fightID" json:"FightID,omitempty"`
	BattleGuid uint32 `protobuf:"varint,5,opt,name=BattleGuid,json=battleGuid" json:"BattleGuid,omitempty"`
	GameID     uint32 `protobuf:"varint,6,opt,name=GameID,json=gameID" json:"GameID,omitempty"`
}

func (m *MsgReConn) Reset()                    { *m = MsgReConn{} }
func (m *MsgReConn) String() string            { return proto.CompactTextString(m) }
func (*MsgReConn) ProtoMessage()               {}
func (*MsgReConn) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *MsgReConn) GetAcc() string {
	if m != nil {
		return m.Acc
	}
	return ""
}

func (m *MsgReConn) GetGuid() uint32 {
	if m != nil {
		return m.Guid
	}
	return 0
}

func (m *MsgReConn) GetToken() uint32 {
	if m != nil {
		return m.Token
	}
	return 0
}

func (m *MsgReConn) GetFightID() uint32 {
	if m != nil {
		return m.FightID
	}
	return 0
}

func (m *MsgReConn) GetBattleGuid() uint32 {
	if m != nil {
		return m.BattleGuid
	}
	return 0
}

func (m *MsgReConn) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgKeyExchange)(nil), "pb.MsgKeyExchange")
	proto.RegisterType((*MsgHeartBeat)(nil), "pb.MsgHeartBeat")
	proto.RegisterType((*MsgGameHeartBeat)(nil), "pb.MsgGameHeartBeat")
	proto.RegisterType((*MsgGameRoles)(nil), "pb.MsgGameRoles")
	proto.RegisterType((*MsgFtHeartBeat)(nil), "pb.MsgFtHeartBeat")
	proto.RegisterType((*MsgGtHeartBeat)(nil), "pb.MsgGtHeartBeat")
	proto.RegisterType((*MsgForwardToRole)(nil), "pb.MsgForwardToRole")
	proto.RegisterType((*MsgROnOffLine)(nil), "pb.MsgROnOffLine")
	proto.RegisterType((*MsgAccInfo)(nil), "pb.MsgAccInfo")
	proto.RegisterType((*MsgLogin)(nil), "pb.MsgLogin")
	proto.RegisterType((*MsgReLogin)(nil), "pb.MsgReLogin")
	proto.RegisterType((*MsgLoginAck)(nil), "pb.MsgLoginAck")
	proto.RegisterType((*MsgLoadRole)(nil), "pb.MsgLoadRole")
	proto.RegisterType((*MsgReConn)(nil), "pb.MsgReConn")
	proto.RegisterEnum("pb.LoginCode", LoginCode_name, LoginCode_value)
}

func init() { proto.RegisterFile("msg_base.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x4d, 0xd3, 0x8f, 0xbb, 0xb6, 0x14, 0x33, 0xa1, 0x88, 0x07, 0xa8, 0x2c, 0x1e, 0x26,
	0x84, 0x26, 0x34, 0x40, 0xbc, 0xb2, 0x25, 0x6b, 0x57, 0xd1, 0x6c, 0x90, 0xee, 0x81, 0x37, 0xe4,
	0x26, 0xb7, 0x6e, 0xd4, 0xd5, 0x9e, 0x62, 0x6f, 0xc0, 0x4f, 0xe1, 0xdf, 0x22, 0xdb, 0xd9, 0x9a,
	0x0d, 0x90, 0xf6, 0x96, 0x73, 0x7d, 0xef, 0x39, 0xe7, 0x1e, 0x5b, 0x81, 0xc1, 0x46, 0xf1, 0xef,
	0x0b, 0xa6, 0x70, 0xff, 0xb2, 0x94, 0x5a, 0x92, 0xc6, 0xe5, 0x82, 0x7e, 0x82, 0x41, 0xa2, 0xf8,
	0x67, 0xfc, 0x75, 0xfc, 0x33, 0x5b, 0x31, 0xc1, 0x91, 0x3c, 0x83, 0xd6, 0xb1, 0xc8, 0x64, 0x8e,
	0xa1, 0x37, 0xf2, 0xf6, 0x48, 0xda, 0x42, 0x8b, 0x4c, 0x3d, 0x46, 0x5b, 0x6f, 0xb8, 0x7a, 0x6e,
	0x11, 0xa5, 0xd0, 0x4b, 0x14, 0x3f, 0x41, 0x56, 0xea, 0x23, 0x64, 0x9a, 0x10, 0x68, 0x9e, 0x17,
	0x9b, 0x9b, 0xe9, 0xa6, 0x2e, 0x36, 0x48, 0x4f, 0x60, 0x98, 0x28, 0x3e, 0x61, 0x1b, 0xdc, 0xf6,
	0x85, 0xd0, 0x4e, 0xe5, 0x05, 0x46, 0x42, 0xdb, 0xd6, 0x27, 0x69, 0xbb, 0x74, 0x90, 0x3c, 0x87,
	0xce, 0xb1, 0xc8, 0xbf, 0xc8, 0x42, 0x68, 0xab, 0xd5, 0x4d, 0x3b, 0x58, 0x61, 0xfa, 0xca, 0xaa,
	0x19, 0x26, 0x33, 0xac, 0xc8, 0x2e, 0x04, 0xf6, 0x23, 0xf4, 0x46, 0xfe, 0x5e, 0x37, 0x0d, 0x0c,
	0x87, 0xa2, 0x6f, 0xec, 0x56, 0x63, 0xbd, 0x55, 0xab, 0x73, 0x7a, 0xf7, 0x38, 0xc7, 0xb6, 0x7b,
	0xf2, 0xb0, 0xee, 0xba, 0xef, 0xc6, 0x1d, 0xdf, 0xf4, 0x9b, 0xdd, 0x72, 0x2c, 0xcb, 0x1f, 0xac,
	0xcc, 0xcf, 0xa5, 0xe9, 0x32, 0xfe, 0x12, 0xc5, 0xa7, 0xb1, 0xa5, 0xe9, 0xa7, 0xc1, 0xc6, 0x00,
	0xc3, 0x6f, 0x4e, 0x27, 0x57, 0x45, 0x6e, 0x49, 0xfa, 0x69, 0xa7, 0xac, 0xb0, 0xc9, 0x2f, 0x66,
	0x9a, 0x85, 0xfe, 0xc8, 0xdb, 0xeb, 0xa5, 0xcd, 0x9c, 0x69, 0x46, 0x3f, 0x40, 0x3f, 0x51, 0x3c,
	0x3d, 0x13, 0x67, 0xcb, 0xe5, 0xac, 0x10, 0x48, 0x86, 0xe0, 0x1f, 0x66, 0x59, 0xe5, 0xcd, 0x67,
	0x59, 0x66, 0xc6, 0x6a, 0x74, 0x4d, 0x7e, 0x55, 0xe4, 0xf4, 0x2d, 0x40, 0xa2, 0xf8, 0x61, 0x96,
	0x4d, 0xc5, 0x52, 0x12, 0x0a, 0xbd, 0x09, 0xd3, 0x78, 0x6f, 0xb1, 0x1e, 0xaf, 0xd5, 0x68, 0x09,
	0x9d, 0x44, 0xf1, 0x99, 0xe4, 0x85, 0xf8, 0x87, 0x46, 0x08, 0xed, 0x39, 0xaa, 0x33, 0x31, 0xd1,
	0x95, 0x4c, 0x5b, 0x39, 0x68, 0xd5, 0xf5, 0x34, 0xb6, 0xa6, 0x8d, 0xba, 0x9e, 0xc6, 0x66, 0x3e,
	0xc6, 0xeb, 0xb0, 0xe9, 0xe6, 0x73, 0xbc, 0x36, 0x61, 0x9c, 0xcb, 0x35, 0x8a, 0x30, 0x70, 0x97,
	0xa5, 0x0d, 0xa0, 0xef, 0xad, 0xcb, 0x14, 0xff, 0xa7, 0xba, 0x0b, 0xc1, 0x1c, 0xd5, 0x34, 0xae,
	0x34, 0x03, 0x65, 0x00, 0x5d, 0xc1, 0xce, 0x8d, 0xd3, 0xc3, 0x6c, 0x4d, 0x5e, 0x82, 0x9f, 0xa2,
	0xdb, 0x69, 0x70, 0xd0, 0xdf, 0xbf, 0x5c, 0xec, 0xdb, 0xa3, 0x48, 0xe6, 0x98, 0xfa, 0x25, 0x6a,
	0x32, 0xaa, 0x62, 0x35, 0x24, 0x3b, 0x07, 0x3d, 0xd3, 0x71, 0x33, 0xef, 0x42, 0x36, 0x0f, 0xdc,
	0xbc, 0xab, 0xdb, 0x2d, 0x5a, 0xdc, 0x22, 0xfa, 0xb1, 0x52, 0x62, 0xb9, 0xbd, 0xd1, 0xbf, 0x0d,
	0x6e, 0x07, 0x1b, 0x77, 0x06, 0x7f, 0x7b, 0xd0, 0xb5, 0x9b, 0x45, 0x52, 0x88, 0x87, 0x5d, 0xd9,
	0x36, 0x22, 0xe7, 0xc1, 0x45, 0x64, 0x82, 0x1f, 0x17, 0x7c, 0x65, 0x12, 0x6e, 0xba, 0xe0, 0x97,
	0x0e, 0x92, 0x17, 0x00, 0x47, 0x4c, 0xeb, 0xea, 0x2d, 0x05, 0xf6, 0x10, 0x16, 0xb7, 0x95, 0x9a,
	0xb7, 0x56, 0xdd, 0xdb, 0xeb, 0xaf, 0xd0, 0xbd, 0x0d, 0x88, 0xf4, 0xa1, 0x3b, 0x8b, 0xe6, 0x57,
	0x59, 0x86, 0x4a, 0x0d, 0x1f, 0x91, 0xa7, 0xf0, 0x78, 0x16, 0xcd, 0xf3, 0x75, 0xb4, 0xc2, 0x6c,
	0x3d, 0x66, 0xc5, 0x45, 0x3e, 0xf4, 0x48, 0x0f, 0x3a, 0xb3, 0xe8, 0x54, 0x1a, 0xb2, 0x61, 0x83,
	0x10, 0x18, 0xcc, 0xa2, 0x88, 0x89, 0x53, 0xa9, 0xdd, 0x7a, 0x43, 0xff, 0xa8, 0x71, 0xe2, 0x2f,
	0x5a, 0xf6, 0xcf, 0xf2, 0xee, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x39, 0x05, 0xb9, 0x6b,
	0x04, 0x00, 0x00,
}
